package com.ipeirotis.readability.enums;

public enum MetricType {
    SMOG, FLESCH_READING, FLESCH_KINCAID, ARI, GUNNING_FOG, COLEMAN_LIAU, SMOG_INDEX, CHARACTERS, SYLLABLES, WORDS, COMPLEXWORDS, SENTENCES;
}
